const HomeActionTypes = {
  SET_LOADING_STATUS: "HOME_ACTIONS/SET_LOADING_STATUS",
  SET_QUERY_PARAMS: "HOME_ACTIONS/SET_QUERY_PARAMS",
  SET_NEW_RELEASES: "HOME_ACTIONS/SET_NEW_RELEASES",
  SET_ARTIST_LIST: "HOME_ACTIONS/SET_ARTIST_LIST",
  SET_SELECTED_ARTIST: "HOME_ACTIONS/SET_SELECTED_ARTIST",
  SET_ARTIST_ALBUMS: "HOME_ACTIONS/SET_ARTIST_ALBUMS",
  SET_SELECTED_ALBUM: "HOME_ACTIONS/SET_SELECTED_ALBUM",
  SET_ALBUM_SONGS: "HOME_ACTIONS/SET_ALBUM_SONGS",
  SET_SELECTED_SONG: "HOME_ACTIONS/SET_SELECTED_SONG",
  SET_PLAY_ALL: "HOME_ACTIONS/SET_PLAY_ALL",
  PLAY_NEXT: "HOME_ACTIONS/PLAY_NEXT",
  PLAY_PREV: "HOME_ACTIONS/PLAY_PREV"
};

export default HomeActionTypes;
